name: "Reputation App CI/CD Pipeline"

on:
  push:
    branches:
    - main

jobs:
  Pipeline-Job:
    name: 'CI Jobs'
    runs-on: ubuntu-latest
    env:
      working-directory: . 
      CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
      CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }} 
      
    steps:

      #Check out repository
    - name: Checkout Code
      uses: actions/checkout@v1

      #Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
      #Install Dependencies      
    - name: Install Relevant Plugins + Dependencies
      run: |
            npm install ejs --save 
            npm install express --save 
            npm install body-parser --save
            npm install node-fetch --save
            npm install http --save
      
      #Scan the code with Shift Left
    - name: ShiftLeft Web Application Code Scan
      run: |
            wget https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.24/shiftleft
            chmod +x shiftleft
            ./shiftleft code-scan -s .
      continue-on-error: true    

      #Smoke test with sample data
    #- name: Test Application Functionality
      #run: |
       #     node server.js
        #    curl -X POST --data "apiKey=${{ secrets.REPUTATION_API_KEY }}" --data "targetUrl=${{ secrets.REPUTATION_TARGET_URL }}" http://localhost:3000  

